name: Check code duplication

on: pull_request_target

jobs:
  duplicate-code-check:
    name: Check for duplicate code
    runs-on: ubuntu-20.04
    steps:
      - name: Check for duplicate code
        uses: platisd/duplicate-code-detection-tool@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file_extensions: "h, hpp, cpp, c, py, cs, js"
          # Only report similarities above 89%
          ignore_below: 89
          # If a file is more than 90% similar to another, then the job fails
          fail_above: 90
          # If a file is more than 91% similar to another, show a warning symbol in the report
          warn_above: 91
          # Leave only one comment with the report and update it for consecutive runs
          one_comment: true
